name: Deploy dev

on:
  push:
    branches: [ develop, bugfix/** ]
  pull_request:
    branches: [ develop ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  packages: read    # This is required for installing dependencies

jobs:
  test:
    name: Test develop
    uses: lomeone/github-action/.github/workflows/gradle-test.yaml@main
    secrets: inherit

  build:
    environment: dev
    name: JIB Build
    needs: [test]
    uses: lomeone/github-action/.github/workflows/gradle-module-jib.yaml@main
    with:
      module-name: application
    secrets: inherit
