name: Deploy staging

on:
  push:
    branches: [ release/** ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  packages: read    # This is required for installing dependencies

jobs:
  build:
    name: JIB Build
    uses: lomeone/github-action/.github/workflows/gradle-module-jib.yaml@main
    with:
      module-name: application
    secrets: inherit

  deploy:
    environment: staging
    name: Deploy develop
    needs: [build]
    runs-on: lomeone-arc-runner-set
    steps:
      - name: Finish deploy
        run: echo "Deployed to staging"
